document.write ("<div>");
document.write ("<div class='text-center mt-3'>");
document.write ("<h4>Prefer to study through mail? <a href='https://amazingbiblestudies.com/by-mail'>Click here to sign up for our correspondence course. </a></h4>");
document.write ("</div>");
document.write ("<hr><div class='text-center mt-3'>Study Bible prophecy through our FREE online Bible School. These proven studies have helped hundreds of thousands unlock the hidden truths of Scripture.</div>");
document.write ("<style>#amazing-bible-studies {font-family: 'Poppins', 'Open Sans', sans-serif; margin: 0 auto;}");
document.write ("#amazing-bible-studies .image{text-align: center;}");
document.write ("#amazing-bible-studies .image .img{max-width: 300px; padding: 20px 10px;margin: 0 auto;}");
document.write ("#amazing-bible-studies .signin{text-align: center;}");
document.write ("#amazing-bible-studies .signin a{display: block;width: 280px;margin: 14px auto;background-color: #055DA7;color: #fff;border-radius: 3px;padding: .5em 2em;box-shadow: 2px 2px 2px rgba(0,0,0,.3);text-decoration: none;font-size: 12px;}");
document.write ("#amazing-bible-studies .signin a:hover{background-color: #05467C;cursor: pointer;}");
document.write ("#amazing-bible-studies .create{text-align: center;}");
document.write ("#amazing-bible-studies .create a{display: block;width: 280px;margin: 14px auto;color: #444;border: 1px #D9D8D8 solid;border-radius: 3px;padding: .5em 2em;box-shadow: 2px 2px 2px rgba(0,0,0,.3);text-decoration: none;font-size: 12px;}");
document.write ("#amazing-bible-studies .create a:hover{background-color: #D7D7D6;border: 1px #AEACAC solid;cursor: pointer;}");
document.write ("</style>");
document.write ("<div id='amazing-bible-studies'>");
document.write ("<div class='image'><img class='img' src='https://manna.amazingfacts.org/amazingfacts/website/biblelms/images/webassets/Logo-AmazingBibleStudies.png'></div>");
document.write ("<div class='signin'><a href='https://amazingbiblestudies.com/sign-in' target='_self'>SIGN IN</a></div>");
document.write ("<div class='create'><a href='https://amazingbiblestudies.com/create-account' target='_self'>CREATE A FREE ACCOUNT</a></div>");
document.write ("</div></div>");